/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#fbf9f4",
        "inverse-primary": "#cac6c1",
        "on-secondary-container": "#795b3c",
        "surface-tint": "#605e5a",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#1c1b18",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "tertiary-container": "#1c1c17",
        "on-primary-container": "#86837f",
        "surface-dim": "#dbdad5",
        "surface-container": "#f0eee9",
        "on-secondary-fixed-variant": "#5c4125",
        "tertiary": "#000000",
        "outline-variant": "#cac6bd",
        "tertiary-fixed-dim": "#c9c6be",
        "on-secondary-fixed": "#2b1701",
        "outline": "#7a776f",
        "on-primary-fixed-variant": "#484743",
        "on-primary": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container-high": "#eae8e3",
        "surface-variant": "#e4e2dd",
        "primary": "#000000",
        "on-tertiary-fixed-variant": "#474741",
        "on-surface-variant": "#494740",
        "primary-fixed-dim": "#cac6c1",
        "secondary": "#77583a",
        "primary-container": "#1c1b18",
        "background": "#fbf9f4",
        "secondary-fixed-dim": "#e7bf9a",
        "on-surface": "#1b1c19",
        "on-error": "#ffffff",
        "surface-bright": "#fbf9f4",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f2f1ec",
        "primary-fixed": "#e6e2dd",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdcbd",
        "surface-container-highest": "#e4e2dd",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e5e2da",
        "on-tertiary-container": "#85847c",
        "secondary-container": "#ffd5af",
        "on-tertiary-fixed": "#1c1c17",
        "on-error-container": "#93000a",
        "on-background": "#1b1c19"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter": "1.5rem",
        "margin-mobile": "1.25rem",
        "space-lg": "1.75rem",
        "margin": "3.5rem",
        "space-xs": "0.25rem",
        "space-xl": "3rem",
        "space-sm": "0.5rem",
        "gutter-mobile": "1rem",
        "space-md": "1rem",
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        "display": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "display-mobile": ["44px", { lineHeight: "52px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["26px", { lineHeight: "34px", letterSpacing: "0em", fontWeight: "400" }],
        "title-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "400" }],
        "label-mono": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
        "label-mono-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
